apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: app-marketplace
spec:
  revisionHistoryLimit: 3
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-marketplace
  template:
    metadata:
      labels:
        app: app-marketplace
    spec:
      containers:
      - name: marketplace
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/marketplace:dev-75c328e
        envFrom:
        - configMapRef:
            name: marketplace-config
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-marketplace
spec:
  selector:
    app: app-marketplace
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketplace
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      server_name ~^(?<subdomain>\w+)\.${HOSTNAME}$;
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($subdomain = '') {
        set $subdomain haus;
      }
      proxy_set_header X-Holaplex-Subdomain $subdomain;
spec:
  ingressClassName: nginx
  rules:
  - host: dev.holaplex.market
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-marketplace
            port:
              number: 3000
  - host: "*.dev.holaplex.market"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-marketplace
            port:
              number: 3000
  tls:
  - hosts:
    - "*.dev.holaplex.market"
    - dev.holaplex.market
